# Generated by Django 2.2.7 on 2019-11-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sightings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=2, help_text='latitude', max_digits=5)),
                ('longitude', models.DecimalField(decimal_places=2, help_text='longitude', max_digits=5)),
                ('Unique_Squirrel_ID', models.IntegerField(help_text='Unique Squirrel_ID')),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], help_text='shift', max_length=16)),
                ('Date', models.DateField(help_text='Date')),
                ('age', models.CharField(choices=[('Adult', 'Adule'), ('Juvenile', 'Juvenile')], help_text='age', max_length=16)),
                ('primary_fur_color', models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'black'), ('White', 'White')], help_text='primary fur color', max_length=16)),
                ('location', models.CharField(choices=[('Ground plane', 'Ground plane'), ('Above ground', 'Above ground')], help_text='location', max_length=16)),
                ('specific_location', models.CharField(help_text='specific location', max_length=100)),
                ('running', models.BooleanField(help_text='running')),
                ('chasing', models.BooleanField(help_text='chasing')),
                ('climbing', models.BooleanField(help_text='climbing')),
                ('eating', models.BooleanField(help_text='eating')),
                ('foraging', models.BooleanField(help_text='foraging')),
                ('other_activities', models.CharField(help_text='other activities', max_length=100)),
                ('kuks', models.BooleanField(help_text='kuks')),
                ('quaas', models.BooleanField(help_text='quaas')),
                ('moans', models.BooleanField(help_text='moans')),
                ('tail_flags', models.BooleanField(help_text='tail flags')),
                ('tail_twitches', models.BooleanField(help_text='tail twitches')),
                ('approaches', models.BooleanField(help_text='approaches')),
                ('indifferent', models.BooleanField(help_text='indifferent')),
                ('runs_from', models.BooleanField(help_text='runs from')),
            ],
        ),
    ]
