# Generated by Django 2.2.7 on 2019-12-08 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sightings',
        ),
    ]
