# Generated by Django 2.2.7 on 2019-12-01 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sightings',
            new_name='squirrels',
        ),
    ]
