# Generated by Django 2.2.7 on 2019-12-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20191201_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrels',
            old_name='longitude',
            new_name='longtitude',
        ),
        migrations.RemoveField(
            model_name='squirrels',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='squirrels',
            name='Unique_Squirrel_ID',
        ),
        migrations.AddField(
            model_name='squirrels',
            name='above_ground_sighter_measurement',
            field=models.CharField(default=False, help_text='Above Ground Sighter Measurement', max_length=9),
        ),
        migrations.AddField(
            model_name='squirrels',
            name='borough_boundaries',
            field=models.CharField(default=None, help_text='Borough Boundaries', max_length=10),
        ),
        migrations.AddField(
            model_name='squirrels',
            name='city_council_districts',
            field=models.CharField(default=None, help_text='City Council Districts', max_length=10),
        ),
        migrations.AddField(
            model_name='squirrels',
            name='color_notes',
            field=models.CharField(blank=True, default='', help_text='Color notes', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='squirrels',
            name='combination',
            field=models.CharField(default='Gray+', help_text='combination', max_length=200),
        ),
        migrations.AddField(
            model_name='squirrels',
            name='community_districts',
            field=models.CharField(default=None, help_text='Community Districts', max_length=10),
        ),
        migrations.AddField(
            model_name='squirrels',
            name='date',
            field=models.DateField(default=None, help_text='Date'),
        ),
        migrations.AddField(
            model_name='squirrels',
            name='hectare',
            field=models.CharField(default=None, help_text='Hectare', max_length=16),
        ),
        migrations.AddField(
            model_name='squirrels',
            name='hectare_squirrel_number',
            field=models.IntegerField(default=None, help_text='Hectare squirrel number '),
        ),
        migrations.AddField(
            model_name='squirrels',
            name='highlight_fur_color',
            field=models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'black'), ('White', 'White')], default='Black', help_text='primary fur color', max_length=16),
        ),
        migrations.AddField(
            model_name='squirrels',
            name='lati_long',
            field=models.CharField(default=None, help_text='lati_long', max_length=100),
        ),
        migrations.AddField(
            model_name='squirrels',
            name='other_interactions',
            field=models.CharField(default=None, help_text='other interactions', max_length=100),
        ),
        migrations.AddField(
            model_name='squirrels',
            name='police_precincts',
            field=models.CharField(default=None, help_text='Police Precincts', max_length=10),
        ),
        migrations.AddField(
            model_name='squirrels',
            name='unique_squirrel_id',
            field=models.CharField(default=None, help_text='Unique Squirrel ID', max_length=200),
        ),
        migrations.AddField(
            model_name='squirrels',
            name='zip_codes',
            field=models.CharField(default=None, help_text='zip codes', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], default='Adult', help_text='age', max_length=16),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='approaches',
            field=models.BooleanField(default=False, help_text='approaches'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='chasing',
            field=models.BooleanField(default=False, help_text='chasing'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='climbing',
            field=models.BooleanField(default=False, help_text='climbing'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='eating',
            field=models.BooleanField(default=False, help_text='eating'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='foraging',
            field=models.BooleanField(default=False, help_text='foraging'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='indifferent',
            field=models.BooleanField(default=False, help_text='indifferent'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='kuks',
            field=models.BooleanField(default=False, help_text='kuks'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='location',
            field=models.CharField(choices=[('Ground plane', 'Ground plane'), ('Above ground', 'Above ground')], default='Ground plane', help_text='location', max_length=16),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='moans',
            field=models.BooleanField(default=False, help_text='moans'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='other_activities',
            field=models.CharField(default=None, help_text='other activities', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='primary_fur_color',
            field=models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'black')], default='Black', help_text='primary fur color', max_length=16),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='quaas',
            field=models.BooleanField(default=False, help_text='quaas'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='running',
            field=models.BooleanField(default=False, help_text='running'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='runs_from',
            field=models.BooleanField(default=False, help_text='runs from'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='shift', max_length=16),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='specific_location',
            field=models.CharField(default=None, help_text='specific location', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='tail_flags',
            field=models.BooleanField(default=False, help_text='tail flags'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='tail_twitches',
            field=models.BooleanField(default=False, help_text='tail twitches'),
        ),
    ]
