# Generated by Django 2.2.7 on 2019-11-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=2, help_text='latitude', max_digits=5)),
                ('longitude', models.DecimalField(decimal_places=2, help_text='longitude', max_digits=5)),
            ],
        ),
    ]
