# Generated by Django 2.2.7 on 2019-11-30 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='longitude',
            new_name='longtitude',
        ),
    ]
