# Generated by Django 2.2.7 on 2019-12-08 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='map',
            new_name='squirrels',
        ),
    ]
